import { Inter } from "@next/font/google";
import { GetStaticProps } from "next";
import Head from "next/head";
import Image from "next/image";
import { useEffect } from "react";
import prisma from "../lib/prisma";
import styles from "../styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ feed }: any) {
  useEffect(() => {
    console.log(feed);
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>posts</h1>
        <div>
          {feed?.map((f: any) => (
            <h1 key={f?.id}>{f?.title}</h1>
          ))}
        </div>
      </div>
    </>
  );
}

// index.tsx
export const getStaticProps: GetStaticProps = async () => {
  const feed = await prisma.post.findMany({
    where: { published: true },
    include: {
      author: {
        select: { name: true },
      },
    },
  });
  return {
    props: { feed },
    revalidate: 10,
  };
};
